[project]
title = "Nicolas Preswald's Coding Assessment"
version = "0.1.0"
port = 8501
slug = "coding-assesment-162306"
entrypoint = "hello.py"

[branding]
name = "Preswald Project"
logo = "images/logo.png"
favicon = "images/informal_seal.ico"
primaryColor = "#e21833"

[data.student_habits_performance]
type = "csv"
path = "data/student_habits_performance.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
